# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'ubuntu-20.04'

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  remote_tag: $(CONTAINERREGISTRYLOGINSERVER)/$(CONTAINERREPOSITORY)/$(CONTAINERNAME):latest

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Image
    steps:
    - task: DockerInstaller@0
      displayName: Install Docker
      inputs:
        dockerVersion: '20.10.5'
    - task: Bash@3
      displayName: Login to azure account
      inputs:
        targetType: 'inline'
        script: |
          az login -u $(AZUREUSERNAME) -p $(AZUREPASSWORD)
    - task: Bash@3
      displayName: Login to container registry
      inputs:
        targetType: 'inline'
        script: |
          az acr login --name $(CONTAINERREGISTRYNAME)
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/src/mongodb/Dockerfile'
        tags: '$(tag)'
    - task: Bash@3
      displayName: Push Image
      inputs:
        targetType: 'inline'
        script: |
          docker image tag $(tagd) $(remote_tag)
          docker push $(remote_tag)
