# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'ubuntu-20.04'

trigger:
- main

resources:
- repo: self

variables:
  container_tag: $(CONTAINERNAME):latest
  remote_tag: $(CONTAINERREGISTRYLOGINSERVER):$(container_tag)

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Image
    steps:
    - task: DockerInstaller@0
      displayName: Install Docker
      inputs:
        dockerVersion: '20.10.5'
    - task: Bash@3
      displayName: Login to Container Registry
      inputs:
        targetType: 'inline'
        script: |
          docker login -u $(AZUREUSERNAME) -p $(AZUREPASSWORD) $(CONTAINERREGISTRYLOGINSERVER)'
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/src/mongodb/Dockerfile'
        tags: |
          $(container-tag)
    - task: Bash@3
      displayName: Push Image
      inputs:
        targetType: 'inline'
        script: |
          docker image tag $(container_tag) $(remote_tag)
          docker push $(remote_tag)
