apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: bookinfo
build:
  local:
    push: false
  artifacts:
    - image: bookinfo-details
      context: src/details
      docker:
        dockerfile: Dockerfile
    - image: bookinfo-productpage
      context: src/productpage
      docker:
        dockerfile: Dockerfile
    - image: bookinfo-ratings
      context: src/ratings
      docker:
        dockerfile: Dockerfile
        buildArgs:
          service_version: v2
    - image: bookinfo-ratings-admin
      context: src/ratings-admin
      docker:
        dockerfile: src/main/docker/Dockerfile.native
    - image: bookinfo-reviews-v1
      context: src/reviews/reviews-wlpcfg
      docker:
        dockerfile: Dockerfile
        buildArgs:
          service_version: v1
    - image: bookinfo-reviews-v2
      context: src/reviews/reviews-wlpcfg
      docker:
        dockerfile: Dockerfile
        buildArgs:
          service_version: v2
          enable_ratings: true
    - image: bookinfo-reviews-v3
      context: src/reviews/reviews-wlpcfg
      docker:
        dockerfile: Dockerfile
        buildArgs:
          service_version: v3
          enable_ratings: true
          star_color: red
    - image: bookinfo-mongodb
      context: src/mongodb
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - platform/bookinfo.yaml
      - platform/bookinfo-db.yaml
      - platform/extras/prometheus.yaml