apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: bookinfo
build:
  local:
    push: false
  artifacts:
    - image: details
      context: src/details
      docker:
        dockerfile: Dockerfile
    - image: productpage
      context: src/productpage
      docker:
        dockerfile: Dockerfile
    - image: ratings
      context: src/ratings
      docker:
        dockerfile: Dockerfile
        buildArgs:
          service_version: v2
    - image: ratings-admin
      context: src/ratings-admin
      docker:
        dockerfile: src/main/docker/Dockerfile.native
    - image: reviews-v1
      context: src/reviews/reviews-wlpcfg
      docker:
        dockerfile: Dockerfile
        buildArgs:
          service_version: v1
    - image: reviews-v2
      context: src/reviews/reviews-wlpcfg
      docker:
        dockerfile: Dockerfile
        buildArgs:
          service_version: v2
          enable_ratings: true
    - image: reviews-v3
      context: src/reviews/reviews-wlpcfg
      docker:
        dockerfile: Dockerfile
        buildArgs:
          service_version: v3
          enable_ratings: true
          star_color: red
    - image: mongodb
      context: src/mongodb
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - kubernetes/platform/bookinfo.yaml
      - kubernetes/platform/bookinfo-db.yaml
      - kubernetes/networking/bookinfo-gateway.yaml