pool:
  vmImage: 'ubuntu-20.04'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - /src/reviews/

resources:
- repo: self

variables:
  remote_tag: $(CONTAINERREGISTRYLOGINSERVER)/$(CONTAINERREPOSITORY)/$(CONTAINERNAME):latest

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Authenticate
    displayname: Authenticate
    steps:
    - task: Bash@3
      displayName: Login to Azure
      inputs:
        targetType: 'inline'
        script: 'az login -u $(AZUREUSERNAME) -p $(AZUREPASSWORD)'
    - task: Bash@3
      displayName: Login to Container Registry
      inputs:
        targetType: 'inline'
        script: 'az acr login --name $(CONTAINERREGISTRYNAME)'
  - job: Build_v1
    displayName: Build/Push v1
    dependsOn: Authenticate
    condition: succeeded()
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/src/reviews/reviews-wlpcfg/Dockerfile'
        arguments: '-t $(remote_tag) --build-arg service_version=v1'
    - task: Bash@3
      displayName: Push Image
      inputs:
        targetType: 'inline'
        script: 'docker push $(remote_tag)'
