pool:
  vmImage: 'ubuntu-20.04'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - /src/reviews/

resources:
- repo: self

variables:
  remote_tag: $(CONTAINERREGISTRYLOGINSERVER)/$(CONTAINERREPOSITORY)/$(CONTAINERNAME)
  remote_tag_v1: $(remote_tag)-v1:latest
  remote_tag_v2: $(remote_tag)-v2:latest
  remote_tag_v3: $(remote_tag)-v3:latest

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildPush
    displayName: Build/Push
    steps:
    - task: Bash@3
      displayName: Login to Azure
      inputs:
        targetType: 'inline'
        script: 'az login -u $(AZUREUSERNAME) -p $(AZUREPASSWORD)'
    - task: Bash@3
      displayName: Login to Container Registry
      inputs:
        targetType: 'inline'
        script: 'az acr login --name $(CONTAINERREGISTRYNAME)'
    - task: Docker@2
      displayName: Build v1
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/src/reviews/reviews-wlpcfg/Dockerfile'
        arguments: '-t $(remote_tag_v1) --build-arg service_version=v1'
    - task: Docker@2
      displayName: Build v2
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/src/reviews/reviews-wlpcfg/Dockerfile'
        arguments: '-t $(remote_tag_v2) --build-arg service_version=v2 --build-arg enable_ratings=true'
    - task: Docker@2
      displayName: Build v3
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/src/reviews/reviews-wlpcfg/Dockerfile'
        arguments: '-t $(remote_tag_v3) --build-arg service_version=v2 --build-arg enable_ratings=true --build-arg star_color=red'
    - task: Bash@3
      displayName: Push v1
      inputs:
        targetType: 'inline'
        script: 'docker push $(remote_tag_v1)'
    - task: Bash@3
      displayName: Push v2
      inputs:
        targetType: 'inline'
        script: 'docker push $(remote_tag_v2)'
    - task: Bash@3
      displayName: Push v3
      inputs:
        targetType: 'inline'
        script: 'docker push $(remote_tag_v3)'
